var tree = [["[Global Namespace]",,"",
                [["b","b.html"," < bolt",
                [        ]],["bolt","bolt.html","",
                [        ]]        ]],["bolt","bolt.html","",
                [["cli","bolt\/cli.html","",
                [["command","bolt\/cli\/command.html"," < Command",
                [        ]]        ]],["client","bolt\/client.html","",
                [["build","bolt\/client\/build.html"," < command",
                [        ]],["command","bolt\/client\/command.html"," < command",
                [        ]],["compile","bolt\/client\/compile.html"," < command",
                [        ]],["deploy","bolt\/client\/deploy.html","",
                [        ]],["models","bolt\/client\/models.html"," < command",
                [        ]]        ]],["dom","bolt\/dom.html","",
                [["element","bolt\/dom\/element.html"," < node",
                [        ]],["fragment","bolt\/dom\/fragment.html"," < dom",
                [        ]],["node","bolt\/dom\/node.html","",
                [        ]],["nodeList","bolt\/dom\/nodeList.html"," < collection",
                [        ]]        ]],["exceptions","bolt\/exceptions.html","",
                [["ResourceNotFoundException","bolt\/exceptions\/ResourceNotFoundException.html"," < Exception",
                [        ]]        ]],["helpers","bolt\/helpers.html","",
                [["events","bolt\/helpers\/events.html","",
                [["event","bolt\/helpers\/events\/event.html","",
                [        ]],["listener","bolt\/helpers\/events\/listener.html","",
                [        ]]        ]],["fs","bolt\/helpers\/fs.html","",
                [["file","bolt\/helpers\/fs\/file.html"," < SplFileObject",
                [        ]],["glob","bolt\/helpers\/fs\/glob.html","",
                [        ]],["rdir","bolt\/helpers\/fs\/rdir.html","",
                [        ]]        ]],["base","bolt\/helpers\/base.html","",
                [        ]],["classes","bolt\/helpers\/classes.html","",
                [        ]],["collection","bolt\/helpers\/collection.html","",
                [        ]],["events","bolt\/helpers\/events.html","",
                [        ]],["fs","bolt\/helpers\/fs.html","",
                [        ]]        ]],["http","bolt\/http.html","",
                [["assets","bolt\/http\/assets.html","",
                [["filters","bolt\/http\/assets\/filters.html","",
                [["cssRewrite","bolt\/http\/assets\/filters\/cssRewrite.html"," < BaseCssFilter",
                [        ]]        ]],["group","bolt\/http\/assets\/group.html","",
                [        ]]        ]],["controller","bolt\/http\/controller.html","",
                [["closure","bolt\/http\/controller\/closure.html"," < route",
                [        ]],["route","bolt\/http\/controller\/route.html"," < controller",
                [        ]]        ]],["middleware","bolt\/http\/middleware.html","",
                [["assets","bolt\/http\/middleware\/assets.html"," < middleware",
                [        ]],["closure","bolt\/http\/middleware\/closure.html"," < middleware",
                [        ]],["direct","bolt\/http\/middleware\/direct.html"," < middleware",
                [        ]],["session","bolt\/http\/middleware\/session.html"," < middleware",
                [        ]]        ]],["response","bolt\/http\/response.html","",
                [["format","bolt\/http\/response\/format.html","",
                [["face","bolt\/http\/response\/format\/face.html","",
                [        ]],["generic","bolt\/http\/response\/format\/generic.html"," < format",
                [        ]],["html","bolt\/http\/response\/format\/html.html"," < format",
                [        ]],["js","bolt\/http\/response\/format\/js.html"," < format",
                [        ]],["json","bolt\/http\/response\/format\/json.html"," < format",
                [        ]],["xhr","bolt\/http\/response\/format\/xhr.html"," < format",
                [        ]],["xml","bolt\/http\/response\/format\/xml.html"," < format",
                [        ]]        ]],["format","bolt\/http\/response\/format.html","",
                [        ]],["redirect","bolt\/http\/response\/redirect.html"," < response",
                [        ]]        ]],["router","bolt\/http\/router.html","",
                [["collection","bolt\/http\/router\/collection.html"," < RouteCollection",
                [        ]],["face","bolt\/http\/router\/face.html","",
                [        ]],["route","bolt\/http\/router\/route.html"," < Route",
                [        ]]        ]],["session","bolt\/http\/session.html","",
                [["middleware","bolt\/http\/session\/middleware.html"," < middleware",
                [        ]],["store","bolt\/http\/session\/store.html","",
                [        ]]        ]],["views","bolt\/http\/views.html","",
                [["compiled","bolt\/http\/views\/compiled.html","",
                [        ]],["face","bolt\/http\/views\/face.html","",
                [        ]],["file","bolt\/http\/views\/file.html","",
                [        ]]        ]],["assets","bolt\/http\/assets.html","",
                [        ]],["controller","bolt\/http\/controller.html","",
                [        ]],["middleware","bolt\/http\/middleware.html","",
                [        ]],["request","bolt\/http\/request.html"," < Request",
                [        ]],["response","bolt\/http\/response.html"," < Response",
                [        ]],["router","bolt\/http\/router.html","",
                [        ]],["session","bolt\/http\/session.html","",
                [        ]],["views","bolt\/http\/views.html","",
                [        ]]        ]],["models","bolt\/models.html","",
                [["functions","bolt\/models\/functions.html","",
                [["findInSet","bolt\/models\/functions\/findInSet.html"," < FunctionNode",
                [        ]],["fromUnixTime","bolt\/models\/functions\/fromUnixTime.html"," < FunctionNode",
                [        ]]        ]],["types","bolt\/models\/types.html","",
                [["stringArray","bolt\/models\/types\/stringArray.html"," < Type",
                [        ]],["timestamp","bolt\/models\/types\/timestamp.html"," < Type",
                [        ]]        ]],["collection","bolt\/models\/collection.html"," < collection",
                [        ]],["driver","bolt\/models\/driver.html","",
                [        ]],["entity","bolt\/models\/entity.html","",
                [        ]],["proxy","bolt\/models\/proxy.html","",
                [        ]]        ]],["plugin","bolt\/plugin.html","",
                [["factory","bolt\/plugin\/factory.html","",
                [        ]],["singleton","bolt\/plugin\/singleton.html","",
                [        ]]        ]],["render","bolt\/render.html","",
                [["xml","bolt\/render\/xml.html","",
                [["generate","bolt\/render\/xml\/generate.html","",
                [        ]]        ]],["base","bolt\/render\/base.html","",
                [        ]],["dom","bolt\/render\/dom.html"," < base",
                [        ]],["handlebars","bolt\/render\/handlebars.html"," < base",
                [        ]],["renderInterface","bolt\/render\/renderInterface.html","",
                [        ]],["xml","bolt\/render\/xml.html"," < base",
                [        ]]        ]],["source","bolt\/source.html","",
                [["curl","bolt\/source\/curl.html","",
                [["repository","bolt\/source\/curl\/repository.html","",
                [        ]]        ]],["curl","bolt\/source\/curl.html","",
                [        ]],["database","bolt\/source\/database.html","",
                [        ]],["event","bolt\/source\/event.html","",
                [        ]],["face","bolt\/source\/face.html","",
                [        ]],["mongodb","bolt\/source\/mongodb.html","",
                [        ]],["sourceInterface","bolt\/source\/sourceInterface.html","",
                [        ]]        ]],["application","bolt\/application.html"," < plugin",
                [        ]],["base","bolt\/base.html","",
                [        ]],["cli","bolt\/cli.html"," < plugin",
                [        ]],["client","bolt\/client.html","",
                [        ]],["config","bolt\/config.html","",
                [        ]],["dom","bolt\/dom.html","",
                [        ]],["http","bolt\/http.html"," < plugin",
                [        ]],["models","bolt\/models.html","",
                [        ]],["plugin","bolt\/plugin.html","",
                [        ]],["render","bolt\/render.html","",
                [        ]]        ]]        ]

