var tree = [["[Global Namespace]",,"",
                [["b","b.html","",
                [        ]],["bolt","bolt.html","",
                [        ]]        ]],["bolt","bolt.html","",
                [["browser","bolt\/browser.html","",
                [["assets","bolt\/browser\/assets.html","",
                [["group","bolt\/browser\/assets\/group.html","",
                [        ]]        ]],["controller","bolt\/browser\/controller.html","",
                [["closure","bolt\/browser\/controller\/closure.html"," < route",
                [        ]],["route","bolt\/browser\/controller\/route.html"," < controller",
                [        ]]        ]],["middleware","bolt\/browser\/middleware.html","",
                [["assets","bolt\/browser\/middleware\/assets.html"," < middleware",
                [        ]],["closure","bolt\/browser\/middleware\/closure.html"," < middleware",
                [        ]]        ]],["response","bolt\/browser\/response.html","",
                [["format","bolt\/browser\/response\/format.html","",
                [["face","bolt\/browser\/response\/format\/face.html","",
                [        ]],["html","bolt\/browser\/response\/format\/html.html"," < format",
                [        ]],["json","bolt\/browser\/response\/format\/json.html"," < format",
                [        ]]        ]],["format","bolt\/browser\/response\/format.html","",
                [        ]],["redirect","bolt\/browser\/response\/redirect.html"," < response",
                [        ]]        ]],["router","bolt\/browser\/router.html","",
                [["collection","bolt\/browser\/router\/collection.html"," < RouteCollection",
                [        ]],["face","bolt\/browser\/router\/face.html","",
                [        ]],["route","bolt\/browser\/router\/route.html"," < Route",
                [        ]]        ]],["views","bolt\/browser\/views.html","",
                [["face","bolt\/browser\/views\/face.html","",
                [        ]],["view","bolt\/browser\/views\/view.html","",
                [        ]]        ]],["assets","bolt\/browser\/assets.html","",
                [        ]],["controller","bolt\/browser\/controller.html","",
                [        ]],["middleware","bolt\/browser\/middleware.html","",
                [        ]],["request","bolt\/browser\/request.html"," < Request",
                [        ]],["response","bolt\/browser\/response.html"," < Response",
                [        ]],["router","bolt\/browser\/router.html","",
                [        ]],["views","bolt\/browser\/views.html","",
                [        ]]        ]],["dom","bolt\/dom.html","",
                [["element","bolt\/dom\/element.html","",
                [        ]],["fragment","bolt\/dom\/fragment.html","",
                [        ]],["nodeList","bolt\/dom\/nodeList.html"," < SplObjectStorage",
                [        ]]        ]],["events","bolt\/events.html","",
                [["event","bolt\/events\/event.html","",
                [        ]],["listener","bolt\/events\/listener.html","",
                [        ]]        ]],["helpers","bolt\/helpers.html","",
                [["fs","bolt\/helpers\/fs.html","",
                [["file","bolt\/helpers\/fs\/file.html"," < SplFileObject",
                [        ]],["glob","bolt\/helpers\/fs\/glob.html"," < GlobIterator",
                [        ]]        ]],["base","bolt\/helpers\/base.html","",
                [        ]],["classes","bolt\/helpers\/classes.html","",
                [        ]],["fs","bolt\/helpers\/fs.html","",
                [        ]]        ]],["models","bolt\/models.html","",
                [["types","bolt\/models\/types.html","",
                [["timestamp","bolt\/models\/types\/timestamp.html"," < Type",
                [        ]]        ]],["driver","bolt\/models\/driver.html","",
                [        ]],["entity","bolt\/models\/entity.html","",
                [        ]],["proxy","bolt\/models\/proxy.html","",
                [        ]],["result","bolt\/models\/result.html"," < SplDoublyLinkedList",
                [        ]]        ]],["plugin","bolt\/plugin.html","",
                [["factory","bolt\/plugin\/factory.html","",
                [        ]],["singleton","bolt\/plugin\/singleton.html","",
                [        ]]        ]],["render","bolt\/render.html","",
                [["base","bolt\/render\/base.html","",
                [        ]],["dom","bolt\/render\/dom.html"," < base",
                [        ]],["handlebars","bolt\/render\/handlebars.html"," < base",
                [        ]]        ]],["source","bolt\/source.html","",
                [["curl","bolt\/source\/curl.html","",
                [["repository","bolt\/source\/curl\/repository.html","",
                [        ]]        ]],["curl","bolt\/source\/curl.html","",
                [        ]],["database","bolt\/source\/database.html","",
                [        ]]        ]],["application","bolt\/application.html"," < plugin",
                [        ]],["browser","bolt\/browser.html"," < plugin",
                [        ]],["config","bolt\/config.html","",
                [        ]],["dom","bolt\/dom.html","",
                [        ]],["events","bolt\/events.html","",
                [        ]],["models","bolt\/models.html","",
                [        ]],["plugin","bolt\/plugin.html","",
                [        ]],["render","bolt\/render.html","",
                [        ]]        ]]        ]

